version: "3.8"

services:
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service/auth
    ports:
      - "8000:8000"
    volumes:
      - ./auth-service/auth:/app
    networks:
      - backend

  appointment_service:
    container_name: appointment_service
    build:
      context: ./appointment_service
    ports:
      - "8002:8002"
    volumes:
      - ./appointment_service:/app
    networks:
      - backend

  medical_service:
    container_name: medical_service
    build:
      context: ./medical_service
    ports:
      - "8003:8003"
    volumes:
      - ./medical_service:/app
    networks:
      - backend

  pharmacist-service:
    container_name: pharmacist-service
    build:
      context: ./pharmacist_service
    ports:
      - "8004:8004"
    volumes:
      - ./pharmacist_service:/app
    networks:
      - backend

  chatbot_service:
    container_name: chatbot_service
    build:
      context: ./chatbot_service
    ports:
      - "8005:8005"
    volumes:
      - ./chatbot_service:/app
    networks:
      - backend

  gateway_service:
    container_name: gateway_service
    build:
      context: ./gateway_service
    ports:
      - "8001:8001"
    volumes:
      - ./gateway_service:/app
    depends_on:
      - auth-service
      - appointment_service
      - medical_service
      - pharmacist-service
      - chatbot_service
    networks:
      - backend

networks:
  backend:
    driver: bridge
