version: "3.8"

services:
  auth-service:
    container_name: auth-service
    build:
      context: ./auth-service/auth
    ports:
      - "8000:8000"
    volumes:
      - ./auth-service/auth:/app
    networks:
      - backend

  patient-service:
    container_name: patient-service
    build:
      context: ./patient_service
    ports:
      - "8002:8002"
    volumes:
      - ./patient_service:/app
    networks:
      - backend

  doctor-service:
    container_name: doctor-service
    build:
      context: ./doctor_service
    ports:
      - "8006:8006"
    volumes:
      - ./doctor_service:/app
    networks:
      - backend

  pharmacist-service:
    container_name: pharmacist-service
    build:
      context: ./pharmacist_service
    ports:
      - "8004:8004"
    volumes:
      - ./pharmacist_service:/app
    networks:
      - backend

  chatbot-service:
    container_name: chatbot-service
    build:
      context: ./chatbot_service
    ports:
      - "8005:8005"
    volumes:
      - ./chatbot_service:/app
    networks:
      - backend

networks:
  backend:
    driver: bridge
